version: "3"
services:
  #  backend:
  #    container_name: backend
  #    restart: always
  #    ports:
  #      - "9000:9000"
  #    expose:
  #      - "9000"
  #    build:
  #      context: ./
  #      dockerfile: ./docker_env/backend/Dockerfile
  #    environment:
  #      TZ: "Asia/Shanghai"
  #    volumes:
  #      - ./backend:/app

  #  admin:
  #    container_name: admin
  #    restart: always
  #    ports:
  #      - "80:80"
  #    expose:
  #      - "80"
  #    image: nginx:latest
  #    environment:
  #      TZ: "Asia/Shanghai"
  #    volumes:
  #      - ./docker_env/admin/nginx/nginx.conf:/etc/nginx/nginx.conf
  #      - ./:/usr/share/nginx/html

  #  task:
  #    container_name: task
  #    restart: always
  #    build:
  #      context: ./
  #      dockerfile: docker_env/task/Dockerfile
  #    environment:
  #      TZ: "Asia/Shanghai"
  #    volumes:
  #      - ./task:/app

  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./docker_env/redis/conf/redis.conf:/etc/redis/redis.conf
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis.conf

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./docker_env/mongo/data:/data/d
      - ./docker_env/mongo/log:/data/log
      - ./docker_env/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # 挂载初始化脚本
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # root 用户名
      MONGO_INITDB_ROOT_PASSWORD: 123456 # root 用户密码
      TZ: "Asia/Shanghai" # 设置时区
    command: mongod --auth --bind_ip 0.0.0.0 # 启用身份验证和允许从任何IP连接

  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./docker_env/mysql/conf:/etc/mysql/conf.d
      - ./docker_env/mysql/data:/var/lib/mysql
      - ./docker_env/mysql/logs:/logs
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "normal"